config/routes.rb
Rails.application.routes.draw do

  resources :experiment_proposals do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_proposal_categories

  resources :reward_categories do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_actions

  resources :resource_reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :providers do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :users do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :resources do
    collection do
      get 'index'
      get 'show'
      get 'get_resources_by_type'
    end
  end

  resources :resource_types do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :nodes do
    collection do
      get 'get_nodes_by_location'
      get 'nodes_by_provider'
      get 'index'
      get 'show'
    end
  end

  resources :function_sets

  resources :interfaces

  resources :data_types

  resources :experiments, :path => '/'

  resources :experiments do
    collection do
      get 'index'
      get 'show'
    end
  end

end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  has_one :resource_type
end

app/models/date_type.rb
class DateType < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_one :experiment_actions
end

app/models/experiment_action.rb
class ExperimentAction < ActiveRecord::Base
  belongs_to :resource_reservation
  belongs_to :experiment
end

app/models/function_set.rb
class FunctionSet < ActiveRecord::Base
  has_one :resource
end

app/models/interface.rb
class Interface < ActiveRecord::Base
  has_many :resource_types
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_one :resource
  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :urn, :presence => true

  def self.get_resources_by_location(latitude,longitude)
    la = BigDecimal(latitude)
    lo = BigDecimal(longitude)
    Node.where(latitude: la,longitude: lo)
  end

  def self.get_nodes_by_provider(provider_id)
    Node.where(provider_id: provider_id)
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  has_many :resource_reservations
  has_many :resources, :through => :resource_reservations
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :function_sets
  belongs_to :nodes
  belongs_to :resource_types
  has_many :resource_reservations
  has_many :reservations, :through => :resource_reservations
  validates :name, :presence => true
  validates :resource_type_id, :presence => true
  validates :function_set_id, :presence => true
  validates :node_id , :presence => true

  def self.resources_by_type(resource_type_id)
    Resource.where(resource_type_id: resource_type_id)
  end

  def self.resources_by_path(path)
    Resource.where(path: path)
  end

  def self.resources_by_name(name)
    Resource.where(name: name)
  end
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
  belongs_to :data_types
  has_one :resource
  validates :name, :presence => true
end

app/models/reward_category.rb
class RewardCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  respond_to :json
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
    respond_with(@nodes) do |format|
      format.json { render :json => @nodes.as_json }
    end
  end

  # GET # /nodes/get_nodes_by_location.json?latitude=46.176388&longitude=6.139959
  def get_nodes_by_location
    @nodes = Node.all
    lat_input = BigDecimal.new(params[:myLocationLat])
    lon_input = BigDecimal.new(params[:myLocationLon])
    distance = 100

    distance = params[:distance] if(params.has_key?(:distance))
    @close_nodes = Array.new
    @nodes.each do |n|
      @close_nodes << n if Harvesine.haversine_distance( lat_input, lon_input, n.latitude, n.longitude ) < distance.to_f
    end

    respond_with(@close_nodes) do |format|
      format.json { render :json => @close_nodes.as_json }
    end
  end

  # GET /nodes/nodes_by_provider.json
  def nodes_by_provider
    @nodes = Node.get_nodes_by_provider(params[:provider_id])
    respond_with(@nodes) do |format|
      format.json { render :json => @nodes.as_json }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :latitude, :longitude, :provider_id, :phone_flag, :urn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_types_helper.rb
module DataTypesHelper
end

app/helpers/date_types_helper.rb
module DateTypesHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :provider_id %><br>
    <%= f.text_field :provider_id %>
  </div>
  <div class="field">
    <%= f.label :phone_flag %><br>
    <%= f.check_box :phone_flag %>
  </div>
  <div class="field">
    <%= f.label :urn %><br>
    <%= f.text_field :urn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>latitude</th>
      <th>longitude</th>
      <th>provider_id</th>
      <th>Phone flag</th>
      <th>Urn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= node.latitude %></td>
        <td><%= node.longitude %></td>
        <td><%= node.provider_id %></td>
        <td><%= node.phone_flag %></td>
        <td><%= node.urn %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>latitude:</strong>
  <%= @node.latitude %>
</p>

<p>
  <strong>longitude:</strong>
  <%= @node.longitude %>
</p>

<p>
  <strong>provider_id:</strong>
  <%= @node.provider_id %>
</p>

<p>
  <strong>Phone flag:</strong>
  <%= @node.phone_flag %>
</p>

<p>
  <strong>Urn:</strong>
  <%= @node.urn %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>