config/routes.rb
Rails.application.routes.draw do

  resources :experiment_proposals do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_proposal_categories

  resources :reward_categories do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_actions

  resources :resource_reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :providers do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :users do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :resources do
    collection do
      get 'index'
      get 'show'
      get 'get_resources_by_type'
    end
  end

  resources :resource_types do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :nodes do
    collection do
      get 'get_nodes_by_location'
      get 'nodes_by_provider'
      get 'index'
      get 'show'
    end
  end

  resources :function_sets

  resources :interfaces

  resources :data_types

  resources :experiments, :path => '/'

  resources :experiments do
    collection do
      get 'index'
      get 'show'
    end
  end

end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  has_one :resource_type
end

app/models/date_type.rb
class DateType < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_one :experiment_actions
end

app/models/experiment_action.rb
class ExperimentAction < ActiveRecord::Base
  belongs_to :resource_reservation
  belongs_to :experiment
end

app/models/experiment_proposal.rb
class ExperimentProposal < ActiveRecord::Base
  belongs_to :experiment_proposal_category
  belongs_to :reward_category
  belongs_to :user
end

app/models/function_set.rb
class FunctionSet < ActiveRecord::Base
  has_one :resource
end

app/models/interface.rb
class Interface < ActiveRecord::Base
  has_many :resource_types
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_one :resource
  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :urn, :presence => true

  def self.get_resources_by_location(latitude,longitude)
    la = BigDecimal(latitude)
    lo = BigDecimal(longitude)
    Node.where(latitude: la,longitude: lo)
  end

  def self.get_nodes_by_provider(provider_id)
    Node.where(provider_id: provider_id)
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  has_many :resource_reservations
  has_many :resources, :through => :resource_reservations
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :function_sets
  belongs_to :nodes
  belongs_to :resource_types
  has_many :resource_reservations
  has_many :reservations, :through => :resource_reservations
  validates :name, :presence => true
  validates :resource_type_id, :presence => true
  validates :function_set_id, :presence => true
  validates :node_id , :presence => true

  def self.resources_by_type(resource_type_id)
    Resource.where(resource_type_id: resource_type_id)
  end

  def self.resources_by_path(path)
    Resource.where(path: path)
  end

  def self.resources_by_name(name)
    Resource.where(name: name)
  end
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
  belongs_to :data_types
  has_one :resource
  validates :name, :presence => true
end

app/models/reward_category.rb
class RewardCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  respond_to :json
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
    respond_with(@experiments) do |format|
      format.json { render :json => @experiments.as_json }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:title, :description, :participation, :devices, :voters, :ranking, :interaction, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_types_helper.rb
module DataTypesHelper
end

app/helpers/date_types_helper.rb
module DateTypesHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :participation %><br>
    <%= f.text_field :participation %>
  </div>
  <div class="field">
    <%= f.label :voters %><br>
    <%= f.number_field :voters %>
  </div>
  <div class="field">
    <%= f.label :ranking %><br>
    <%= f.text_field :ranking %>
  </div>
  <div class="field">
    <%= f.label :interaction %><br>
    <%= f.text_field :interaction %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<h1>Listing experiments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Participation</th>
      <th>Voters</th>
      <th>Ranking</th>
      <th>Interaction</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.title %></td>
        <td><%= experiment.description %></td>
        <td><%= experiment.participation %></td>
        <td><%= experiment.voters %></td>
        <td><%= experiment.ranking %></td>
        <td><%= experiment.interaction %></td>
        <td><%= experiment.status %></td>
        <td><%= link_to 'Show', experiment %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
        <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experiment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experiment.description %>
</p>

<p>
  <strong>Participation:</strong>
  <%= @experiment.participation %>
</p>

<p>
  <strong>Voters:</strong>
  <%= @experiment.voters %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @experiment.ranking %>
</p>

<p>
  <strong>Interaction:</strong>
  <%= @experiment.interaction %>
</p>

<p>
  <strong>Status:</strong>
  <%= @experiment.status %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>