config/routes.rb
Rails.application.routes.draw do

  resources :experiment_proposals do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_proposal_categories

  resources :reward_categories do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_actions

  resources :resource_reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :providers do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :users do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :resources do
    collection do
      get 'index'
      get 'show'
      get 'get_resources_by_type'
    end
  end

  resources :resource_types do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :nodes do
    collection do
      get 'get_nodes_by_location'
      get 'nodes_by_provider'
      get 'index'
      get 'show'
    end
  end

  resources :function_sets

  resources :interfaces

  resources :data_types

  resources :experiments, :path => '/'

  resources :experiments do
    collection do
      get 'index'
      get 'show'
    end
  end

end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  has_one :resource_type
end

app/models/date_type.rb
class DateType < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_one :experiment_actions
end

app/models/experiment_action.rb
class ExperimentAction < ActiveRecord::Base
  belongs_to :resource_reservation
  belongs_to :experiment
end

app/models/function_set.rb
class FunctionSet < ActiveRecord::Base
  has_one :resource
end

app/models/interface.rb
class Interface < ActiveRecord::Base
  has_many :resource_types
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_one :resource
  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :urn, :presence => true

  def self.get_resources_by_location(latitude,longitude)
    la = BigDecimal(latitude)
    lo = BigDecimal(longitude)
    Node.where(latitude: la,longitude: lo)
  end

  def self.get_nodes_by_provider(provider_id)
    Node.where(provider_id: provider_id)
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  has_many :resource_reservations
  has_many :resources, :through => :resource_reservations
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :function_sets
  belongs_to :nodes
  belongs_to :resource_types
  has_many :resource_reservations
  has_many :reservations, :through => :resource_reservations
  validates :name, :presence => true
  validates :resource_type_id, :presence => true
  validates :function_set_id, :presence => true
  validates :node_id , :presence => true

  def self.resources_by_type(resource_type_id)
    Resource.where(resource_type_id: resource_type_id)
  end

  def self.resources_by_path(path)
    Resource.where(path: path)
  end

  def self.resources_by_name(name)
    Resource.where(name: name)
  end
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
  belongs_to :data_types
  has_one :resource
  validates :name, :presence => true
end

app/models/reward_category.rb
class RewardCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/helpers/data_types_helper.rb
module DataTypesHelper
end

app/helpers/date_types_helper.rb
module DateTypesHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iotlabbackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ipso_index %><br>
    <%= f.number_field :ipso_index %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.number_field :name %>
  </div>
  <div class="field">
    <%= f.label :function_set_id_id %><br>
    <%= f.text_field :function_set_id_id %>
  </div>
  <div class="field">
    <%= f.label :node_id %><br>
    <%= f.text_field :node_id %>
  </div>
  <div class="field">
    <%= f.label :resource_type_id %><br>
    <%= f.text_field :resource_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Ipso index</th>
      <th>Function set</th>
      <th>Node</th>
      <th>Resource type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.ipso_index %></td>
        <td><%= resource.name %></td>
        <td><%= resource.function_set_id %></td>
        <td><%= resource.node_id %></td>
        <td><%= resource.resource_type_id %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ipso index:</strong>
  <%= @resource.ipso_index %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Function set:</strong>
  <%= @resource.function_set_id %>
</p>

<p>
  <strong>Node:</strong>
  <%= @resource.node_id %>
</p>

<p>
  <strong>Resource type:</strong>
  <%= @resource.resource_type_id %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>