config/routes.rb
Rails.application.routes.draw do

  resources :experiment_proposals do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_proposal_categories

  resources :reward_categories do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :experiment_actions

  resources :resource_reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :reservations do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :providers do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :users do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :resources do
    collection do
      get 'index'
      get 'show'
      get 'get_resources_by_type'
    end
  end

  resources :resource_types do
    collection do
      get 'index'
      get 'show'
    end
  end

  resources :nodes do
    collection do
      get 'get_nodes_by_location'
      get 'nodes_by_provider'
      get 'index'
      get 'show'
    end
  end

  resources :function_sets

  resources :interfaces

  resources :data_types

  resources :experiments, :path => '/'

  resources :experiments do
    collection do
      get 'index'
      get 'show'
    end
  end

end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  has_one :resource_type
end

app/models/date_type.rb
class DateType < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_one :experiment_actions
end

app/models/experiment_action.rb
class ExperimentAction < ActiveRecord::Base
  belongs_to :resource_reservation
  belongs_to :experiment
end

app/models/function_set.rb
class FunctionSet < ActiveRecord::Base
  has_one :resource
end

app/models/interface.rb
class Interface < ActiveRecord::Base
  has_many :resource_types
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_one :resource
  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :urn, :presence => true

  def self.get_resources_by_location(latitude,longitude)
    la = BigDecimal(latitude)
    lo = BigDecimal(longitude)
    Node.where(latitude: la,longitude: lo)
  end

  def self.get_nodes_by_provider(provider_id)
    Node.where(provider_id: provider_id)
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  has_many :resource_reservations
  has_many :resources, :through => :resource_reservations
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :function_sets
  belongs_to :nodes
  belongs_to :resource_types
  has_many :resource_reservations
  has_many :reservations, :through => :resource_reservations
  validates :name, :presence => true
  validates :resource_type_id, :presence => true
  validates :function_set_id, :presence => true
  validates :node_id , :presence => true

  def self.resources_by_type(resource_type_id)
    Resource.where(resource_type_id: resource_type_id)
  end

  def self.resources_by_path(path)
    Resource.where(path: path)
  end

  def self.resources_by_name(name)
    Resource.where(name: name)
  end
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
  belongs_to :data_types
  has_one :resource
  validates :name, :presence => true
end

app/models/reward_category.rb
class RewardCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/function_sets_controller.rb
class FunctionSetsController < ApplicationController
  before_action :set_function_set, only: [:show, :edit, :update, :destroy]

  # GET /function_sets
  # GET /function_sets.json
  def index
    @function_sets = FunctionSet.all
  end

  # GET /function_sets/1
  # GET /function_sets/1.json
  def show
  end

  # GET /function_sets/new
  def new
    @function_set = FunctionSet.new
  end

  # GET /function_sets/1/edit
  def edit
  end

  # POST /function_sets
  # POST /function_sets.json
  def create
    @function_set = FunctionSet.new(function_set_params)

    respond_to do |format|
      if @function_set.save
        format.html { redirect_to @function_set, notice: 'Function set was successfully created.' }
        format.json { render :show, status: :created, location: @function_set }
      else
        format.html { render :new }
        format.json { render json: @function_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /function_sets/1
  # PATCH/PUT /function_sets/1.json
  def update
    respond_to do |format|
      if @function_set.update(function_set_params)
        format.html { redirect_to @function_set, notice: 'Function set was successfully updated.' }
        format.json { render :show, status: :ok, location: @function_set }
      else
        format.html { render :edit }
        format.json { render json: @function_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /function_sets/1
  # DELETE /function_sets/1.json
  def destroy
    @function_set.destroy
    respond_to do |format|
      format.html { redirect_to function_sets_url, notice: 'Function set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function_set
      @function_set = FunctionSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def function_set_params
      params.require(:function_set).permit(:name, :restype, :description, :root_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_types_helper.rb
module DataTypesHelper
end

app/helpers/date_types_helper.rb
module DateTypesHelper
end

app/helpers/function_sets_helper.rb
module FunctionSetsHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/function_sets/_form.html.erb
<%= form_for(@function_set) do |f| %>
  <% if @function_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function_set.errors.count, "error") %> prohibited this function_set from being saved:</h2>

      <ul>
      <% @function_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :restype %><br>
    <%= f.text_field :restype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :root_path %><br>
    <%= f.text_field :root_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/function_sets/edit.html.erb
<h1>Editing function_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @function_set %> |
<%= link_to 'Back', function_sets_path %>

app/views/function_sets/index.html.erb
<h1>Listing function_sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Restype</th>
      <th>Description</th>
      <th>Root path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @function_sets.each do |function_set| %>
      <tr>
        <td><%= function_set.name %></td>
        <td><%= function_set.restype %></td>
        <td><%= function_set.description %></td>
        <td><%= function_set.root_path %></td>
        <td><%= link_to 'Show', function_set %></td>
        <td><%= link_to 'Edit', edit_function_set_path(function_set) %></td>
        <td><%= link_to 'Destroy', function_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Function set', new_function_set_path %>

app/views/function_sets/new.html.erb
<h1>New function_set</h1>

<%= render 'form' %>

<%= link_to 'Back', function_sets_path %>

app/views/function_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @function_set.name %>
</p>

<p>
  <strong>Restype:</strong>
  <%= @function_set.restype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @function_set.description %>
</p>

<p>
  <strong>Root path:</strong>
  <%= @function_set.root_path %>
</p>

<%= link_to 'Edit', edit_function_set_path(@function_set) %> |
<%= link_to 'Back', function_sets_path %>